### ISSUE TITLE
G06

### ISSUE THREAD

**Issue by Steve092** [ZapdoZ/numberstations#3]
Hello, any chance we could see G06 or similar older german numbers stations being added in the future?
I'm asking as I found sample files of the old speech/morse generator which was extensively used by the Ministerium of Staatssicherheit (stasi) in east germany and later in various other numbers stations
https://www.cryptomuseum.com/spy/owvl/32620/index.htm#voice
Nevertheless, thank you very much and best regards!

**Comment by ZapdoZ** [comment]
Thanks for the link to the voice assets, I will use them.

Yes, the plan was indeed to start implementing stations generated by the Gerät 32620 in the next updates. I haven't been working on this project for a while, but I definitely plan on continuing it. I do have other projects at the time, so I can't guarantee when the next update will be.

**Comment by ZapdoZ** [comment]
The new release [v1 Alpha 2](https://github.com/ZapdoZ/numberstations/releases/tag/v1-alpha-2) now includes G06.
Timing isn't perfect yet, I will probably improve that in a later release.
